version: "3"
services:
  api:
    build: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - APP_PORT=:8080
      - DB_ADDR=db:6379
      - DB_PASS=
      - DOMAIN=localhost:8080
      - API_QUOTA=10

  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data